services:
  # 1. SERVIDOR WEB (NGINX)
  nginx:
    image: nginx:alpine
    container_name: whatever_nginx
    ports:
      - "8080:80"   # HTTP
      - "8443:443"  # HTTPS
    volumes:
      - ./:/var/www/html
      - ./.podman/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - php

  # 2. INTÃ‰RPRETE PHP (FPM)
  php:
    build: .
    image: localhost/tnp_php_fpm:latest
    container_name: tnp_php
    volumes:
      - ./:/var/www/html

  # 3. BASE DE DATOS
  db:
    image: docker.io/library/mariadb:10.11
    container_name: whatever_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: whatever_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
