services:
  # 1. SERVIDOR WEB (NGINX)
  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_nginx
    restart: unless-stopped
    network_mode: service:php
    volumes:
      - ./:/var/www/html
      - ./.podman/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - php

  # 2. INTÃ‰RPRETE PHP (FPM)
  php:
    build: .
    image: localhost/${PROJECT_NAME}_php_fpm:latest
    container_name: ${PROJECT_NAME}_php
    restart: unless-stopped
    ports:
      - "8080:80"   # HTTP
      - "8443:443"  # HTTPS
    volumes:
      - ./:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  # 3. BASE DE DATOS
  db:
    image: docker.io/library/mariadb:10.11
    container_name: ${PROJECT_NAME}_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  db_data:

networks:
  default:
    name: ${PROJECT_NAME}_network
